/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.brml.BRMLRuntimeModule;
import org.xtext.example.brml.BRMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BRMLIdeSetup extends BRMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BRMLRuntimeModule(), new BRMLIdeModule()));
	}
	
}
