/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.brml.BRML.ui.internal.BRMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BRMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BRMLActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BRMLActivator activator = BRMLActivator.getInstance();
		return activator != null ? activator.getInjector(BRMLActivator.ORG_XTEXT_EXAMPLE_BRML_BRML) : null;
	}

}
