/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BRMLStandaloneSetup extends BRMLStandaloneSetupGenerated {

	public static void doSetup() {
		new BRMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
