/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.brml.bRML.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BRMLFactoryImpl extends EFactoryImpl implements BRMLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BRMLFactory init()
  {
    try
    {
      BRMLFactory theBRMLFactory = (BRMLFactory)EPackage.Registry.INSTANCE.getEFactory(BRMLPackage.eNS_URI);
      if (theBRMLFactory != null)
      {
        return theBRMLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BRMLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BRMLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BRMLPackage.MODEL: return createModel();
      case BRMLPackage.OPERATION: return createOperation();
      case BRMLPackage.STOP: return createStop();
      case BRMLPackage.DEL_STOP: return createDelStop();
      case BRMLPackage.ROUTE: return createRoute();
      case BRMLPackage.ROUTE_STOP: return createRouteStop();
      case BRMLPackage.BUS: return createBus();
      case BRMLPackage.DEL_ROUTE: return createDelRoute();
      case BRMLPackage.DEL_BUS: return createDelBus();
      case BRMLPackage.LOCATION: return createLocation();
      case BRMLPackage.ADD_ROUTE_STOP: return createAddRouteStop();
      case BRMLPackage.DELETE_ROUTE_STOP: return createDeleteRouteStop();
      case BRMLPackage.PRINT_ROUTE: return createPrintRoute();
      case BRMLPackage.PRINT_BUS: return createPrintBus();
      case BRMLPackage.PRINT_STOP: return createPrintStop();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stop createStop()
  {
    StopImpl stop = new StopImpl();
    return stop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DelStop createDelStop()
  {
    DelStopImpl delStop = new DelStopImpl();
    return delStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Route createRoute()
  {
    RouteImpl route = new RouteImpl();
    return route;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RouteStop createRouteStop()
  {
    RouteStopImpl routeStop = new RouteStopImpl();
    return routeStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bus createBus()
  {
    BusImpl bus = new BusImpl();
    return bus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DelRoute createDelRoute()
  {
    DelRouteImpl delRoute = new DelRouteImpl();
    return delRoute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DelBus createDelBus()
  {
    DelBusImpl delBus = new DelBusImpl();
    return delBus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Location createLocation()
  {
    LocationImpl location = new LocationImpl();
    return location;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddRouteStop createAddRouteStop()
  {
    AddRouteStopImpl addRouteStop = new AddRouteStopImpl();
    return addRouteStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeleteRouteStop createDeleteRouteStop()
  {
    DeleteRouteStopImpl deleteRouteStop = new DeleteRouteStopImpl();
    return deleteRouteStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrintRoute createPrintRoute()
  {
    PrintRouteImpl printRoute = new PrintRouteImpl();
    return printRoute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrintBus createPrintBus()
  {
    PrintBusImpl printBus = new PrintBusImpl();
    return printBus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrintStop createPrintStop()
  {
    PrintStopImpl printStop = new PrintStopImpl();
    return printStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BRMLPackage getBRMLPackage()
  {
    return (BRMLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BRMLPackage getPackage()
  {
    return BRMLPackage.eINSTANCE;
  }

} //BRMLFactoryImpl
