/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.brml.bRML.BRMLPackage;
import org.xtext.example.brml.bRML.DeleteRouteStop;
import org.xtext.example.brml.bRML.Route;
import org.xtext.example.brml.bRML.Stop;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Delete Route Stop</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.impl.DeleteRouteStopImpl#getRouteStop <em>Route Stop</em>}</li>
 *   <li>{@link org.xtext.example.brml.bRML.impl.DeleteRouteStopImpl#getRoute <em>Route</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeleteRouteStopImpl extends OperationImpl implements DeleteRouteStop
{
  /**
   * The cached value of the '{@link #getRouteStop() <em>Route Stop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRouteStop()
   * @generated
   * @ordered
   */
  protected Stop routeStop;

  /**
   * The cached value of the '{@link #getRoute() <em>Route</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoute()
   * @generated
   * @ordered
   */
  protected Route route;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeleteRouteStopImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BRMLPackage.Literals.DELETE_ROUTE_STOP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stop getRouteStop()
  {
    if (routeStop != null && routeStop.eIsProxy())
    {
      InternalEObject oldRouteStop = (InternalEObject)routeStop;
      routeStop = (Stop)eResolveProxy(oldRouteStop);
      if (routeStop != oldRouteStop)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP, oldRouteStop, routeStop));
      }
    }
    return routeStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Stop basicGetRouteStop()
  {
    return routeStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRouteStop(Stop newRouteStop)
  {
    Stop oldRouteStop = routeStop;
    routeStop = newRouteStop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP, oldRouteStop, routeStop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Route getRoute()
  {
    if (route != null && route.eIsProxy())
    {
      InternalEObject oldRoute = (InternalEObject)route;
      route = (Route)eResolveProxy(oldRoute);
      if (route != oldRoute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, BRMLPackage.DELETE_ROUTE_STOP__ROUTE, oldRoute, route));
      }
    }
    return route;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Route basicGetRoute()
  {
    return route;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoute(Route newRoute)
  {
    Route oldRoute = route;
    route = newRoute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BRMLPackage.DELETE_ROUTE_STOP__ROUTE, oldRoute, route));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP:
        if (resolve) return getRouteStop();
        return basicGetRouteStop();
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE:
        if (resolve) return getRoute();
        return basicGetRoute();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP:
        setRouteStop((Stop)newValue);
        return;
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE:
        setRoute((Route)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP:
        setRouteStop((Stop)null);
        return;
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE:
        setRoute((Route)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE_STOP:
        return routeStop != null;
      case BRMLPackage.DELETE_ROUTE_STOP__ROUTE:
        return route != null;
    }
    return super.eIsSet(featureID);
  }

} //DeleteRouteStopImpl
