/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Route Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.AddRouteStop#getRouteStop <em>Route Stop</em>}</li>
 *   <li>{@link org.xtext.example.brml.bRML.AddRouteStop#getRoute <em>Route</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getAddRouteStop()
 * @model
 * @generated
 */
public interface AddRouteStop extends Operation
{
  /**
   * Returns the value of the '<em><b>Route Stop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Route Stop</em>' reference.
   * @see #setRouteStop(Stop)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getAddRouteStop_RouteStop()
   * @model
   * @generated
   */
  Stop getRouteStop();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.AddRouteStop#getRouteStop <em>Route Stop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Route Stop</em>' reference.
   * @see #getRouteStop()
   * @generated
   */
  void setRouteStop(Stop value);

  /**
   * Returns the value of the '<em><b>Route</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Route</em>' reference.
   * @see #setRoute(Route)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getAddRouteStop_Route()
   * @model
   * @generated
   */
  Route getRoute();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.AddRouteStop#getRoute <em>Route</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Route</em>' reference.
   * @see #getRoute()
   * @generated
   */
  void setRoute(Route value);

} // AddRouteStop
