/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.brml.bRML.BRMLPackage
 * @generated
 */
public interface BRMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BRMLFactory eINSTANCE = org.xtext.example.brml.bRML.impl.BRMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stop</em>'.
   * @generated
   */
  Stop createStop();

  /**
   * Returns a new object of class '<em>Del Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Del Stop</em>'.
   * @generated
   */
  DelStop createDelStop();

  /**
   * Returns a new object of class '<em>Route</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Route</em>'.
   * @generated
   */
  Route createRoute();

  /**
   * Returns a new object of class '<em>Route Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Route Stop</em>'.
   * @generated
   */
  RouteStop createRouteStop();

  /**
   * Returns a new object of class '<em>Bus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bus</em>'.
   * @generated
   */
  Bus createBus();

  /**
   * Returns a new object of class '<em>Del Route</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Del Route</em>'.
   * @generated
   */
  DelRoute createDelRoute();

  /**
   * Returns a new object of class '<em>Del Bus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Del Bus</em>'.
   * @generated
   */
  DelBus createDelBus();

  /**
   * Returns a new object of class '<em>Location</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location</em>'.
   * @generated
   */
  Location createLocation();

  /**
   * Returns a new object of class '<em>Add Route Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Route Stop</em>'.
   * @generated
   */
  AddRouteStop createAddRouteStop();

  /**
   * Returns a new object of class '<em>Delete Route Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Route Stop</em>'.
   * @generated
   */
  DeleteRouteStop createDeleteRouteStop();

  /**
   * Returns a new object of class '<em>Print Route</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Route</em>'.
   * @generated
   */
  PrintRoute createPrintRoute();

  /**
   * Returns a new object of class '<em>Print Bus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Bus</em>'.
   * @generated
   */
  PrintBus createPrintBus();

  /**
   * Returns a new object of class '<em>Print Stop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Stop</em>'.
   * @generated
   */
  PrintStop createPrintStop();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BRMLPackage getBRMLPackage();

} //BRMLFactory
