/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Del Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.DelStop#getStop <em>Stop</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getDelStop()
 * @model
 * @generated
 */
public interface DelStop extends Operation
{
  /**
   * Returns the value of the '<em><b>Stop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop</em>' reference.
   * @see #setStop(Stop)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getDelStop_Stop()
   * @model
   * @generated
   */
  Stop getStop();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.DelStop#getStop <em>Stop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop</em>' reference.
   * @see #getStop()
   * @generated
   */
  void setStop(Stop value);

} // DelStop
