/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.Location#getLatitude <em>Latitude</em>}</li>
 *   <li>{@link org.xtext.example.brml.bRML.Location#getLongitude <em>Longitude</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getLocation()
 * @model
 * @generated
 */
public interface Location extends EObject
{
  /**
   * Returns the value of the '<em><b>Latitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Latitude</em>' attribute.
   * @see #setLatitude(String)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getLocation_Latitude()
   * @model
   * @generated
   */
  String getLatitude();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.Location#getLatitude <em>Latitude</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Latitude</em>' attribute.
   * @see #getLatitude()
   * @generated
   */
  void setLatitude(String value);

  /**
   * Returns the value of the '<em><b>Longitude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Longitude</em>' attribute.
   * @see #setLongitude(String)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getLocation_Longitude()
   * @model
   * @generated
   */
  String getLongitude();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.Location#getLongitude <em>Longitude</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Longitude</em>' attribute.
   * @see #getLongitude()
   * @generated
   */
  void setLongitude(String value);

} // Location
