/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
} // Operation
