/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Bus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.PrintBus#getBus <em>Bus</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getPrintBus()
 * @model
 * @generated
 */
public interface PrintBus extends Operation
{
  /**
   * Returns the value of the '<em><b>Bus</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bus</em>' reference.
   * @see #setBus(Bus)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getPrintBus_Bus()
   * @model
   * @generated
   */
  Bus getBus();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.PrintBus#getBus <em>Bus</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bus</em>' reference.
   * @see #getBus()
   * @generated
   */
  void setBus(Bus value);

} // PrintBus
