/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Route Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.RouteStop#getRoutestop <em>Routestop</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getRouteStop()
 * @model
 * @generated
 */
public interface RouteStop extends EObject
{
  /**
   * Returns the value of the '<em><b>Routestop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Routestop</em>' reference.
   * @see #setRoutestop(Stop)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getRouteStop_Routestop()
   * @model
   * @generated
   */
  Stop getRoutestop();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.RouteStop#getRoutestop <em>Routestop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Routestop</em>' reference.
   * @see #getRoutestop()
   * @generated
   */
  void setRoutestop(Stop value);

} // RouteStop
