/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.bRML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.brml.bRML.Stop#getStop <em>Stop</em>}</li>
 *   <li>{@link org.xtext.example.brml.bRML.Stop#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.brml.bRML.BRMLPackage#getStop()
 * @model
 * @generated
 */
public interface Stop extends Operation
{
  /**
   * Returns the value of the '<em><b>Stop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop</em>' attribute.
   * @see #setStop(String)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getStop_Stop()
   * @model
   * @generated
   */
  String getStop();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.Stop#getStop <em>Stop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop</em>' attribute.
   * @see #getStop()
   * @generated
   */
  void setStop(String value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference.
   * @see #setLocation(Location)
   * @see org.xtext.example.brml.bRML.BRMLPackage#getStop_Location()
   * @model containment="true"
   * @generated
   */
  Location getLocation();

  /**
   * Sets the value of the '{@link org.xtext.example.brml.bRML.Stop#getLocation <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' containment reference.
   * @see #getLocation()
   * @generated
   */
  void setLocation(Location value);

} // Stop
