/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.brml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BRMLUiModule extends AbstractBRMLUiModule {

	public BRMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
